config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'search_items#index'
  resources :search_items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search_item.rb
# frozen_string_literal: true

class SearchItem < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/search_items_controller.rb
# frozen_string_literal: true

# Controller that provides RESTful operations on search items. Users have access to GET operations, except GET new, at the moment.
class SearchItemsController < ApplicationController
  before_action :set_search_item, only: %i[show edit update destroy]

  # User accessible
  # Searchable via keywords provided in search item model
  # GET /search_items
  # GET /search_items.json
  def index
    @search_items = SearchItem.all

    @search_items = SearchItem.where(['keywords LIKE ?', "%#{params[:search]}%"])
  end

  # User accessible
  # GET /search_items/1
  # GET /search_items/1.json
  def show; end

  # GET /search_items/new
  def new
    @search_item = SearchItem.new
  end

  # GET /search_items/1/edit
  def edit; end

  # POST /search_items
  # POST /search_items.json
  def create
    @search_item = SearchItem.new(search_item_params)

    respond_to do |format|
      if @search_item.save
        format.html { redirect_to @search_item, notice: 'Search item was successfully created.' }
        format.json { render :show, status: :created, location: @search_item }
      else
        format.html { render :new }
        format.json { render json: @search_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /search_items/1
  # PATCH/PUT /search_items/1.json
  def update
    respond_to do |format|
      if @search_item.update(search_item_params)
        format.html { redirect_to @search_item, notice: 'Search item was successfully updated.' }
        format.json { render :show, status: :ok, location: @search_item }
      else
        format.html { render :edit }
        format.json { render json: @search_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /search_items/1
  # DELETE /search_items/1.json
  def destroy
    @search_item.destroy
    respond_to do |format|
      format.html { redirect_to search_items_url, notice: 'Search item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_search_item
    @search_item = SearchItem.find(params[:id])
  end

  # Only allow list of trusted parameters through.
  def search_item_params
    params.require(:search_item).permit(:title, :text, :link, :keywords)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_items_helper.rb
module SearchItemsHelper
end

app/views/layouts/application.html.erb
<html lang="en">
  <head>
    <title>SearchySearch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css2?family=Oxygen&display=swap','application.css' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css2?family=Crimson+Text&display=swap','application.css' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <nav class="nav-bar">
    <h3><a href="/">Le Searchy Search</a></h3>
  </nav>
  <body>
    <%= yield %>
  </body>
  <footer>
    <div id="navbar-b">Made with &#10084 for BB</div>
  </footer>
</html>

app/views/search_items/_form.html.erb
<%= form_with(model: search_item, local: true) do |form| %>
  <% if search_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(search_item.errors.count, "error") %> prohibited this search_item from being saved:</h2>

      <ul>
        <% search_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_area :link %>
  </div>

  <div class="field">
    <%= form.label :keywords %>
    <%= form.text_area :keywords %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/search_items/edit.html.erb
<h1>Editing Search Item</h1>

<%= render 'form', search_item: @search_item %>

<%= link_to 'Show', @search_item %> |
<%= link_to 'Back', search_items_path %> |
<%= link_to 'Delete', @search_item, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/search_items/index.html.erb
<p class="navbar-text float-right">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
</p>
<p id="notice"><%= notice %></p>

<table>
  <thead>
  <%= stylesheet_link_tag 'application', "https://fonts.googleapis.com/css?family=Oxygen"%>
    <tr>
    </tr>
  </thead>

  <tbody>
    <main>
      <section id="search">
       <div id="search-container">
        <div id="header">
          <h1>Le Searchy Search</h1>
        </div>
        <h4>Search here by keyword:</h4>
        <%= form_tag(search_items_path, method: :get) do %>  
          <div id="search-field">
            <%= text_field_tag(:search, params[:search]) %> <br>
            <%= submit_tag ("Search") %>
          </div>
        <% end %>
        </div>
      </section>
    <% @search_items.each do |search_item| %>
      <tr>
      <ul id="results">
      <li><%= link_to search_item.title, search_item_path(search_item) %></li><br>
      </ul>
      </tr>
    <% end %>
    </main>
  </tbody>
</table>

app/views/search_items/new.html.erb
<h1>New Search Item</h1>

<%= render 'form', search_item: @search_item %>

<%= link_to 'Back', search_items_path %>

app/views/search_items/show.html.erb
<p id="notice"><%= notice %></p>

<main id="show-card">
<p>
  <strong>Title:</strong>
  <%= @search_item.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @search_item.text %>
</p>

<p>
  <strong>Link:</strong>
  <%= link_to 'Link to document', (@search_item.link), :target => "_blank" %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @search_item.keywords %>
</p>

|
<%= link_to 'Back', root_path, data: {turbolinks: false} %>
|

</main>